CREATE DATABASE UNIONBANK;


CREATE SCHEMA BORROWER

CREATE TABLE BORROWER.BORROWER (
BorrowerID INT NOT NULL,
BORROWERFIRSTNAME VARCHAR (255) NOT NULL,
BORROWERMINITIALS CHAR (1) NOT NULL,
BORROWERLASTNAME VARCHAR (255) NOT NULL,
DOB DATETIME NOT NULL,
GENDER CHAR (1) NOT NULL,
TAXPAYERID_SSN VARCHAR (9) NOT NULL,
PHONENUMBER VARCHAR (10) NOT NULL,
EMAIL VARCHAR (255) NOT NULL,
CITIZENSHIP VARCHAR (255) NULL,
BENEFICIARYNAME VARCHAR (255) NULL,
IsUsCitizen BIT NULL,
CreateDate DATETIME NOT NULL);



CREATE TABLE BORROWER.BORROWERADDRESS (
AddressID INT NOT NULL,
BorrowerID INT NOT NULL,
StreetAddress VARCHAR (255) NOT NULL,
Zip VARCHAR (5) NOT NULL,
CreateDate DATETIME NOT NULL);



CREATE TABLE CALENDAR (
CalendarDate DATETIME NULL);



CREATE TABLE [STATE] (
StateID CHAR (2) NOT NULL,
StateName VARCHAR (255) NOT NULL,
CreateDate DATETIME NOT NULL)



CREATE TABLE US_ZIPCODES (
IsSurrogateKey INT NOT NULL,
ZIP VARCHAR (5) NOT NULL,
Latitude FLOAT NULL,
Longtitude FLOAT NULL,
City VARCHAR (255) NULL,
State_ID CHAR (2) NULL,
[Population] INT NULL,
Density DECIMAL (18,0) NULL,
County_fips VARCHAR (10) NULL,
County_Name VARCHAR (255) NULL,
County_Names_All VARCHAR (255),
County_Fips_All VARCHAR (50) NULL,
TimeZone VARCHAR (255) NULL,
CreateDate DATETIME NOT NULL);



CREATE SCHEMA LOAN

CREATE TABLE LOAN.LOANSETUPINFORMATION (
IsSurrogateKey INT NOT NULL,
LOANNUMBER VARCHAR (10) NOT NULL,
PURCHASEAMOUNT NUMERIC (18,2) NOT NULL,
PURCSHASEDATE DATETIME NOT NULL,
LOANTERM INT NOT NULL,
BORROWERID INT NOT NULL,
UNDERWRITERID INT NOT NULL,
PRODUCTID CHAR (2) NOT NULL,
INTERESTRATE DECIMAL (3,2) NOT NULL,
PAYMENTFREQUENCY INT NOT NULL,
APPRAISALVALUE NUMERIC (18,2) NOT NULL,
CREATEDATE DATETIME NOT NULL,
LTV DECIMAL (4,2) NOT NULL,
FIRSTINTERESTPAYMENTDATE DATETIME NULL,
MATURITYDATE DATETIME NOT NULL) 


CREATE TABLE LOAN.LOANPERIODIC (
Issurrogatekey INT NOT NULL,
Loannumber VARCHAR (10) NOT NULL,
Cycledate DATETIME NOT NULL,
Extramonthlypayment NUMERIC (18,2) NOT NULL,
Unpaidprincipalbalance NUMERIC (18,2) NOT NULL,
Beginningschedulebalance NUMERIC (18,2) NOT NULL,
Paidinstallment NUMERIC (18,2) NOT NULL,
Interestportion NUMERIC (18,2) NOT NULL,
Principalportion NUMERIC (18,2) NOT NULL,
Endschedulebalance NUMERIC (18,2) NOT NULL, 
Actualendschedulebalance NUMERIC (18,2) NOT NULL,
Totalinterestaccrued NUMERIC (18,2) NOT NULL,
Totalprincipalaccrued NUMERIC (18,2) NOT NULL, 
DEFAULTPENALTY NUMERIC (18,2) NOT NULL,
Delinquencycode INT IDENTITY (10,10) NOT NULL, --- increament by 0, added code to identity, requirement given was 10,0
Createdate  DATETIME NOT NULL);


CREATE TABLE LOAN.LU_DELINQUENCY (
DELINQUENCYCODE INT NOT NULL,
DELINQUENCY VARCHAR (255) NOT NULL)


CREATE TABLE LOAN.LU_PAYMENTFREQUENCY (
PAYMENTFREQUENCY INT NOT NULL,
PAYMENTISMADEEVERY INT NOT NULL,
PAYMENTFREQUENCY_DESCRIPTION VARCHAR (255) NOT NULL)


CREATE TABLE LOAN.UNDERWRITER (
UnderwriterID INT NOT NULL,
UnderwriterFirstName VARCHAR (255) NULL,
UnderwriterMiddleInitial CHAR (1) NULL,
UnderwriterLastName VARCHAR (255) NOT NULL,
PhoneNumber VARCHAR (14) NULL, 
Email VARCHAR (255) NULL,
CreateDate DATETIME NOT NULL)



---- Alter Tables.

ALTER TABLE BORROWER.BORROWER
ADD CONSTRAINT PK_BORROWERID PRIMARY KEY (BORROWERID);


ALTER TABLE BORROWER.BORROWER
ADD CONSTRAINT UC_BORROWERID UNIQUE (BORROWERID);


ALTER TABLE BORROWER.BORROWERADDRESS
ADD CONSTRAINT PK_BORROWERADDRESS_ADDRESSID_BORROWERID PRIMARY KEY (ADDRESSID,BORROWERID);


ALTER TABLE LOAN.LOANPERIODIC
ADD CONSTRAINT PK_LOANPERIODIC_LOANNUMBER_CYCLEDATE PRIMARY KEY (LOANNUMBER,CYCLEDATE);


ALTER TABLE LOAN.LOANSETUPINFORMATION
ADD CONSTRAINT PK_LOANSETUPINFORMATION_LOANNUMBER PRIMARY KEY (LOANNUMBER);


ALTER TABLE LOAN.LU_DELINQUENCY
ADD CONSTRAINT PK_LOANLU_DELINQUENCY_DELINQUENCYCODE PRIMARY KEY (DELINQUENCYCODE);


ALTER TABLE [LOAN].[LU_PAYMENTFREQUENCY]
ADD CONSTRAINT PK_LU_PAYMENTFREQUENCY PRIMARY KEY ([PAYMENTFREQUENCY]);
 


ALTER TABLE DBO.[STATE]
ADD CONSTRAINT PK_STATE_STATEID PRIMARY KEY (STATEID);


ALTER TABLE LOAN.UNDERWRITER
ADD CONSTRAINT PK_LOANUNDERWRITER_UNDERWRITERID PRIMARY KEY (UNDERWRITERID);


ALTER TABLE DBO.US_ZIPCODES
ADD CONSTRAINT PK_US_ZIPCODES PRIMARY KEY (ZIP);


ALTER TABLE BORROWER.BORROWER
ADD CONSTRAINT CHK_BORROWER_DOB CHECK (DOB <= dateadd(year,-18 , getdate()));


ALTER TABLE BORROWER.BORROWER
ADD CONSTRAINT CHK_EMAIL CHECK (EMAIL LIKE '%@%');


ALTER TABLE BORROWER.BORROWER
ADD CONSTRAINT CHK_PHONENUMBER  CHECK (LEN (PHONENUMBER) =10);


ALTER TABLE BORROWER.BORROWER
ADD CONSTRAINT CHK_TAXPAYERID_SSN CHECK (LEN (TAXPAYERID_SSN) =9);


ALTER TABLE BORROWER.BORROWER
ADD CONSTRAINT DF_CREATEDATE DEFAULT (GETDATE ()) FOR CREATEDATE;


ALTER TABLE BORROWER.BORROWERADDRESS
ADD CONSTRAINT DF_BORROWER_CREATEDATE DEFAULT (GETDATE ()) FOR CREATEDATE; 


ALTER TABLE BORROWER.BORROWERADDRESS
ADD CONSTRAINT FK_BORROWERID FOREIGN KEY (BORROWERID) REFERENCES BORROWER.BORROWER(BORROWERID);


ALTER TABLE BORROWER.BORROWERADDRESS
ADD CONSTRAINT FK_BORROWERADDRESS_ZIP FOREIGN KEY (ZIP) REFERENCES US_ZIPCODES (ZIP);


alter table LOAN.LOANPERIODIC
add constraint chk_loanperiodic_interestportion_principalportion check (interestportion+Principalportion=Paidinstallment)
 

alter table LOAN.LOANPERIODIC
add constraint df_loanperiodic_createdate default (getdate()) for Createdate


alter table LOAN.LOANPERIODIC
add constraint df_loanperiodic_extramonthlypayment default (0) for Extramonthlypayment 


alter table LOAN.LOANPERIODIC
add constraint fk_loanperiodic_loannumber foreign key (Loannumber) references loan.LoanSetUpInformation (LoanNumber) 


alter table LOAN.LOANPERIODIC
add constraint fk_loanperiodic_delinquencycode foreign key (DelinquencyCode) references loan.lu_delinquency (Delinquencycode)


alter table LOAN.LOANSETUPINFORMATION
add constraint chk_loansetupinformation_loanterm check (loanterm in(35,30,15,10)) 


ALTER TABLE LOAN.LOANSETUPINFORMATION
ADD CONSTRAINT CHK_LOANSETUPINFORMATION CHECK (INTERESTRATE BETWEEN 0.01 and 0.30);


ALTER TABLE LOAN.LOANSETUPINFORMATION
ADD CONSTRAINT DF_CREATEDATE DEFAULT (GETDATE ()) FOR CREATEDATE;


ALTER TABLE LOAN.LOANSETUPINFORMATION
ADD CONSTRAINT FK_BORROWERID FOREIGN KEY (BORROWERID) REFERENCES BORROWER.BORROWER (BORROWERID);


ALTER TABLE LOAN.LOANSETUPINFORMATION
ADD CONSTRAINT FK_PAYMENTFREQUENCY FOREIGN KEY (PAYMENTFREQUENCY) REFERENCES LOAN.LU_PAYMENTFREQUENCY (PAYMENTFREQUENCY);


ALTER TABLE LOAN.LOANSETUPINFORMATION
ADD CONSTRAINT FK_LOAN_UNDERWRITERID FOREIGN KEY (UNDERWRITERID) REFERENCES LOAN.UNDERWRITER (UNDERWRITERID);


ALTER TABLE DBO.[STATE]
ADD CONSTRAINT DF_STATE_CREATEDATE DEFAULT (GETDATE ()) FOR CREATEDATE;


ALTER TABLE DBO.[STATE]
ADD CONSTRAINT UC_STATE_STATENAME UNIQUE (STATENAME);


ALTER TABLE LOAN.UNDERWRITER
ADD CONSTRAINT CHK_LOAN_EMAIL CHECK (EMAIL LIKE '%@%');


ALTER TABLE LOAN.UNDERWRITER
ADD CONSTRAINT DF_LOAN_CREATEDATE DEFAULT (GETDATE ()) FOR CREATEDATE;


ALTER TABLE DBO.US_ZIPCODES
ADD CONSTRAINT DF_US_ZIPCODES_CREATEDATE DEFAULT (GETDATE ()) FOR CREATEDATE;


ALTER TABLE DBO.US_ZIPCODES
ADD CONSTRAINT FK_US_ZIPCODES_STATEID FOREIGN KEY (STATE_ID) REFERENCES LOAN.UNDERWRITER (UNDERWRITERID);
--ERROR Column 'LOAN.UNDERWRITER.UnderwriterID' is not the same data type as referencing column 'US_ZIPCODES.STATE_ID' in foreign key 'FK_US_ZIPCODES_STATEID'

